### ISSUE TITLE
white list doesn't work properly

### ISSUE THREAD

**Issue by rutaka-n** [funbox/fitting#10]
I try to use white_list like this:
```    
config.white_list = {
      '/smth' => ['GET']
    }
```
but in `fitting/stats` file  this resourse placed in black list.

then I use white list like this:
```
    config.resource_white_list = {
      '/smth' => ['GET /api/v1/smth']
    }
```
and this works properly, but why I need to specify api prefix in array with methods descriptions?
Might be will be better to omit api prefix in this part too?

thank you for you time!

**Comment by rutaka-n** [comment]
I am not sure that it is still actual. If not, please close issue. @tuwilof 
have a nice day!

**Comment by tuwilof** [comment]
Thanks!
