### ISSUE TITLE
Zsh support

### ISSUE THREAD

**Issue by SofaKing18** [funbox/fitting#23]
Have trouble with zsh terminal wrapper:

```
➜  bundle exec rake fitting:tests_responses[xs]
zsh: no matches found: fitting:tests_responses[xs]
➜  bundle exec rake fitting:tests_responses
need key xs
```

in bash all OK

Is there another way to set the size key?

**Comment by SofaKing18** [comment]
Seems like the problem is square brackets

**Comment by SofaKing18** [comment]
Thank you!

What about add alternative launch (more classical) like listed below:
```
bundle exec rake fitting:tests_responses size:xs
or 
bundle exec rake fitting:tests_responses --size xs
```

**Comment by danilobarion1986** [comment]
> Yes. Please use single quotes:
> 
> ```
> bundle exec rake 'fitting:tests_responses[xs]'
> ```
Even using like this (or escaping the brackets, I'm still getting this error (Manjaro Linux / oh-my-zsh):
`RAILS_ENV=test bundle exec rake 'fitting:tests_responses[xs]'
/home/danilo/.rbenv/versions/2.5.3/gemsets/sasson/bin/rake: No such file or directory - drafter
rake aborted!
TypeError: no implicit conversion of nil into String
/home/danilo/.rbenv/versions/2.5.3/gemsets/sasson/gems/psych-3.1.0/lib/psych.rb:456:in `parse'
/home/danilo/.rbenv/versions/2.5.3/gemsets/sasson/gems/psych-3.1.0/lib/psych.rb:456:in `parse_stream'
/home/danilo/.rbenv/versions/2.5.3/gemsets/sasson/gems/psych-3.1.0/lib/psych.rb:390:in `parse'
/home/danilo/.rbenv/versions/2.5.3/gemsets/sasson/gems/psych-3.1.0/lib/psych.rb:349:in `safe_load'
/home/danilo/.rbenv/versions/2.5.3/gemsets/sasson/gems/tomograph-2.4.2/lib/tomograph/api_blueprint/yaml.rb:11:in `initialize'
/home/danilo/.rbenv/versions/2.5.3/gemsets/sasson/gems/tomograph-2.4.2/lib/tomograph/tomogram.rb:14:in `new'
/home/danilo/.rbenv/versions/2.5.3/gemsets/sasson/gems/tomograph-2.4.2/lib/tomograph/tomogram.rb:14:in `initialize'
/home/danilo/.rbenv/versions/2.5.3/gemsets/sasson/gems/fitting-2.8.1/lib/fitting/configuration/yaml.rb:34:in `new'
/home/danilo/.rbenv/versions/2.5.3/gemsets/sasson/gems/fitting-2.8.1/lib/fitting/configuration/yaml.rb:34:in `tomogram'
/home/danilo/.rbenv/versions/2.5.3/gemsets/sasson/gems/fitting-2.8.1/lib/tasks/fitting.rake:103:in `block (2 levels) in <main>'
/home/danilo/.rbenv/versions/2.5.3/gemsets/sasson/gems/airbrake-8.3.2/lib/airbrake/rake.rb:17:in `execute'
/home/danilo/.rbenv/versions/2.5.3/gemsets/sasson/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
/home/danilo/.rbenv/versions/2.5.3/gemsets/sasson/gems/bundler-1.17.3/lib/bundler/cli/exec.rb:74:in `load'
/home/danilo/.rbenv/versions/2.5.3/gemsets/sasson/gems/bundler-1.17.3/lib/bundler/cli/exec.rb:74:in `kernel_load'
/home/danilo/.rbenv/versions/2.5.3/gemsets/sasson/gems/bundler-1.17.3/lib/bundler/cli/exec.rb:28:in `run'
/home/danilo/.rbenv/versions/2.5.3/gemsets/sasson/gems/bundler-1.17.3/lib/bundler/cli.rb:463:in `exec'
/home/danilo/.rbenv/versions/2.5.3/gemsets/sasson/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/danilo/.rbenv/versions/2.5.3/gemsets/sasson/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/home/danilo/.rbenv/versions/2.5.3/gemsets/sasson/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/home/danilo/.rbenv/versions/2.5.3/gemsets/sasson/gems/bundler-1.17.3/lib/bundler/cli.rb:27:in `dispatch'
/home/danilo/.rbenv/versions/2.5.3/gemsets/sasson/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/home/danilo/.rbenv/versions/2.5.3/gemsets/sasson/gems/bundler-1.17.3/lib/bundler/cli.rb:18:in `start'
/home/danilo/.rbenv/versions/2.5.3/gemsets/sasson/gems/bundler-1.17.3/exe/bundle:30:in `block in <top (required)>'
/home/danilo/.rbenv/versions/2.5.3/gemsets/sasson/gems/bundler-1.17.3/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
/home/danilo/.rbenv/versions/2.5.3/gemsets/sasson/gems/bundler-1.17.3/exe/bundle:22:in `<top (required)>'
/home/danilo/.rbenv/versions/2.5.3/gemsets/sasson/bin/bundle:23:in `load'
/home/danilo/.rbenv/versions/2.5.3/gemsets/sasson/bin/bundle:23:in `<main>'
Tasks: TOP => fitting:tests_responses
(See full trace by running task with --trace)`

**Comment by tuwilof** [comment]
> > Yes. Please use single quotes:
> > ```
> > bundle exec rake 'fitting:tests_responses[xs]'
> > ```
> 
> Even using like this (or escaping the brackets), I'm still getting this error (Manjaro Linux / oh-my-zsh):
> 
> `RAILS_ENV=test bundle exec rake 'fitting:tests_responses[xs]'`
> 
> `/home/danilo/.rbenv/versions/2.5.3/gemsets/sasson/bin/rake: No such file or directory - drafter rake aborted! TypeError: no implicit conversion of nil into String /home/danilo/.rbenv/versions/2.5.3/gemsets/sasson/gems/psych-3.1.0/lib/psych.rb:456:in `parse'
> /home/danilo/.rbenv/versions/2.5.3/gemsets/sasson/gems/psych-3.1.0/lib/psych.rb:456:in `parse_stream' /home/danilo/.rbenv/versions/2.5.3/gemsets/sasson/gems/psych-3.1.0/lib/psych.rb:390:in `parse'
> /home/danilo/.rbenv/versions/2.5.3/gemsets/sasson/gems/psych-3.1.0/lib/psych.rb:349:in `safe_load' /home/danilo/.rbenv/versions/2.5.3/gemsets/sasson/gems/tomograph-2.4.2/lib/tomograph/api_blueprint/yaml.rb:11:in `initialize'
> /home/danilo/.rbenv/versions/2.5.3/gemsets/sasson/gems/tomograph-2.4.2/lib/tomograph/tomogram.rb:14:in `new' /home/danilo/.rbenv/versions/2.5.3/gemsets/sasson/gems/tomograph-2.4.2/lib/tomograph/tomogram.rb:14:in `initialize'
> /home/danilo/.rbenv/versions/2.5.3/gemsets/sasson/gems/fitting-2.8.1/lib/fitting/configuration/yaml.rb:34:in `new' /home/danilo/.rbenv/versions/2.5.3/gemsets/sasson/gems/fitting-2.8.1/lib/fitting/configuration/yaml.rb:34:in `tomogram'
> /home/danilo/.rbenv/versions/2.5.3/gemsets/sasson/gems/fitting-2.8.1/lib/tasks/fitting.rake:103:in `block (2 levels) in <main>' /home/danilo/.rbenv/versions/2.5.3/gemsets/sasson/gems/airbrake-8.3.2/lib/airbrake/rake.rb:17:in `execute'
> /home/danilo/.rbenv/versions/2.5.3/gemsets/sasson/gems/rake-12.3.2/exe/rake:27:in `<top (required)>' /home/danilo/.rbenv/versions/2.5.3/gemsets/sasson/gems/bundler-1.17.3/lib/bundler/cli/exec.rb:74:in `load'
> /home/danilo/.rbenv/versions/2.5.3/gemsets/sasson/gems/bundler-1.17.3/lib/bundler/cli/exec.rb:74:in `kernel_load' /home/danilo/.rbenv/versions/2.5.3/gemsets/sasson/gems/bundler-1.17.3/lib/bundler/cli/exec.rb:28:in `run'
> /home/danilo/.rbenv/versions/2.5.3/gemsets/sasson/gems/bundler-1.17.3/lib/bundler/cli.rb:463:in `exec' /home/danilo/.rbenv/versions/2.5.3/gemsets/sasson/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
> /home/danilo/.rbenv/versions/2.5.3/gemsets/sasson/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command' /home/danilo/.rbenv/versions/2.5.3/gemsets/sasson/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
> /home/danilo/.rbenv/versions/2.5.3/gemsets/sasson/gems/bundler-1.17.3/lib/bundler/cli.rb:27:in `dispatch' /home/danilo/.rbenv/versions/2.5.3/gemsets/sasson/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
> /home/danilo/.rbenv/versions/2.5.3/gemsets/sasson/gems/bundler-1.17.3/lib/bundler/cli.rb:18:in `start' /home/danilo/.rbenv/versions/2.5.3/gemsets/sasson/gems/bundler-1.17.3/exe/bundle:30:in `block in <top (required)>'
> /home/danilo/.rbenv/versions/2.5.3/gemsets/sasson/gems/bundler-1.17.3/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors' /home/danilo/.rbenv/versions/2.5.3/gemsets/sasson/gems/bundler-1.17.3/exe/bundle:22:in `<top (required)>'
> /home/danilo/.rbenv/versions/2.5.3/gemsets/sasson/bin/bundle:23:in `load' /home/danilo/.rbenv/versions/2.5.3/gemsets/sasson/bin/bundle:23:in `
> 
> '
> Tasks: TOP => fitting:tests_responses
> (See full trace by running task with --trace)`

You need to install https://github.com/apiaryio/drafter

**Comment by tuwilof** [comment]
Thanks to everyone, we improved the README
https://github.com/funbox/fitting/commit/1bf110878c06d40b983dec74c103eeeb54452cfc
https://github.com/funbox/fitting/commit/7a733a4c6803242b776e67d6db86bd943e220d14
