### ISSUE TITLE
Use github actions for CI instead of Travis

### ISSUE THREAD

**Issue by rutaka-n** [funbox/fitting#30]
Travis is not cool anymore. ;)

**Comment by nicktime** [comment]
"А чо так можно было что ли?!!" Круто)

**Comment by tuwilof** [comment]
@rutaka-n whats up? why? what is cool?

**Comment by tuwilof** [comment]
@nicktime what do you mean?
p/s we are an international gem :trollface:, english please)

**Comment by tuwilof** [comment]
@StoneGod :trollface: :

**Comment by tuwilof** [comment]
@rutaka-n oh, you're talking about github ci, yeah interesting

**Comment by rutaka-n** [comment]
> @rutaka-n whats up? why? what is cool?)

As I know Travis schedules opensource free account's jobs with lowest priority.
Same time, Github Actions is native way for making CI pipelines for github =)

And I think you should try to use it!

p/s I have not use it yet by myself =)

**Comment by StoneGod** [comment]
Travis works - do not touch

**Comment by hyrintalion** [comment]
Travis isn't needed!

**Comment by tuwilof** [comment]
@vassilevsky @SemkArt @climber73 what do you think? 🤔

**Comment by tuwilof** [comment]
@rutaka-n @hyrintalion I was told that github ci is temporarily free and there are no guarantees for open source 😱

**Comment by rutaka-n** [comment]
RLY?
https://help.github.com/en/actions/automating-your-workflow-with-github-actions/about-github-actions#usage-limits

**Comment by climber73** [comment]
How's it look like when your project is under Github Actions? Is it beautiful? Can anybody provide a link to a repo with Github Actions integrated?

**Comment by tuwilof** [comment]
I added github actions for CI in current repo.
But I won't delete Travis yet, it takes time to compare.
Recently found an article, it might be interesting
https://medium.com/@cakeinpanic/github-actions-база-2501445e7392

**Comment by tuwilof** [comment]
it's true, github actions better than travis
faster and less problems, but CD is still difficult
